"""
Django settings for multiverseclothing project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project's .env file.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@!-*%+fkkezq3ixa0qr!dxwz+_o#5-$_mkerk@&@5*1f^oi8qn"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "https://miniature-gianna-risheb-s-3f8e4c84.koyeb.app",  # Replace with your actual Koyeb URL
    "http://miniature-gianna-risheb-s-3f8e4c84.koyeb.app",
    "https://eccomerce-app-rishebss3113-2o7p5w58.leapcell.dev",
    "http://eccomerce-app-rishebss3113-2o7p5w58.leapcell.dev",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "credentials",
    "productapp",
    "custom",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "multiverseclothing.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "multiverseclothing.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# PostgreSQL database configuration.
# Prefers DATABASE_URL (postgresql://user:pass@host:port/name?sslmode=...);
# falls back to the individual DB_* variables. Query parameters are passed
# through as connection OPTIONS. sslnegotiation is dropped because the bundled
# psycopg2/libpq here rejects it ("invalid connection option").
def _database_config():
    options = {}
    url = os.environ.get("DATABASE_URL")
    if url:
        parsed = urlparse(url)
        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or ""),
        }
        for key, values in parse_qsl(parsed.query):
            if key == "sslnegotiation":
                continue
            options[key] = values
    else:
        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", ""),
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", ""),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
        if os.environ.get("DB_SSLMODE"):
            options["sslmode"] = os.environ["DB_SSLMODE"]

    if options:
        config["OPTIONS"] = options
    return config


DATABASES = {"default": _database_config()}

if not DATABASES["default"]["NAME"]:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "No database configured. Set DATABASE_URL (or DB_NAME and related "
        "DB_* variables) in the environment or in the project's .env file."
    )


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.StaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

RAZORPAY_KEY_ID = "rzp_test_dTWp25pBQ5jW81"
RAZORPAY_KEY_SECRET = "Sg6ymJfWNf4atGBsqXhuaALE"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Leapcell Storage (S3-compatible)
AWS_ACCESS_KEY_ID = os.environ.get(
    "LEAPCELL_ACCESS_KEY_ID", "1cdcae51c65a4ccfac712aabe881cea8"
)
AWS_SECRET_ACCESS_KEY = os.environ.get("LEAPCELL_SECRET_KEY", "")
AWS_STORAGE_BUCKET_NAME = os.environ.get(
    "LEAPCELL_BUCKET_NAME", "os-wsp2007474520584683520-anjs-freg-wgwaxlrx"
)
AWS_S3_ENDPOINT_URL = os.environ.get(
    "LEAPCELL_ENDPOINT", "https://objstorage.leapcell.io"
)
AWS_S3_REGION_NAME = os.environ.get("LEAPCELL_REGION", "us-east-1")
AWS_DEFAULT_ACL = "public-read"
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
AWS_QUERYSTRING_AUTH = False

# Media files storage
MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
